spring:
  profiles:
    active: prod
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  datasource:
    druid:
      wjcrm:
        initial-size: 5
        max-active: 10
        min-idle: 5
        max-wait: 6000
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        url: 'jdbc:db2://155.101.252.196:50000/WJDB'
        username: db2inst1
        password: db2admin
server:
  port: 10006
logging:
  config: classpath:logback-prod.xml
debug: true


file:
  upload:
    #path: /home/data_vol/
    path: D:/data_vol
  url: http://155.101.252.196:10006/resource